Controllers/BreadcrumbsAdminController.cs
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using Onestop.Navigation.Breadcrumbs.Models;
using Onestop.Navigation.Breadcrumbs.Services;
using Onestop.Navigation.Breadcrumbs.ViewModels;
using Onestop.Patterns.Services;
using Orchard;
using Orchard.Environment.Extensions;
using Orchard.Localization;
using Orchard.Security;
using Orchard.UI.Admin;
using Orchard.UI.Notify;

namespace Onestop.Navigation.Controllers
{
    [OrchardFeature("Onestop.Navigation.Breadcrumbs")]
    [Admin]
    public class BreadcrumbsAdminController : Controller
    {
        private readonly IOrchardServices _services;
        private readonly IPatternService _patterns;
        private readonly INotifier _notifier;
        private readonly IBreadcrumbsService _breadcrumbs;

        public BreadcrumbsAdminController(
            IOrchardServices services, 
            IPatternService patterns, 
            INotifier notifier, 
            IBreadcrumbsService breadcrumbs)
        {
            _services = services;
            _patterns = patterns;
            _notifier = notifier;
            _breadcrumbs = breadcrumbs;
            T = NullLocalizer.Instance;
        }

        public Localizer T { get; set; }

        [HttpGet]
        public ActionResult Index()
        {
            var model = new BreadcrumbsIndexViewModel()
                            {
                                Matches = new Dictionary<string, PatternMatch>(),
                                Patterns = _breadcrumbs.GetPatterns(),
                                Providers = _breadcrumbs.GetProviderDescriptors()
                            };
            return View(model);
        }

        [HttpPost]
        [ActionName("Index")]
        public ActionResult IndexPOST(BreadcrumbsIndexViewModel model)
        {
            model.Patterns = _breadcrumbs.GetPatterns();
            model.Providers = _breadcrumbs.GetProviderDescriptors();
            foreach (var pattern in model.Patterns)
            {
                PatternMatch match;
                _patterns.TryMatch(model.TestString, pattern.Pattern, out match);
                model.Matches[pattern.Pattern] = match;
            }

            return View(model);
        }

        [HttpPost]
        [ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeletePOST(int id, string returnUrl)
        {
            if (!_services.Authorizer.Authorize(StandardPermissions.SiteOwner))
                return new HttpUnauthorizedResult();

            _breadcrumbs.DeletePattern(id);
            _notifier.Information(T("Entry deleted successfully!"));

            return Redirect(returnUrl);
        }

        [HttpPost]
        [ActionName("Add")]
        [ValidateAntiForgeryToken]
        public ActionResult AddPOST(string pattern, string provider, string returnUrl)
        {
            if (!_services.Authorizer.Authorize(StandardPermissions.SiteOwner))
                return new HttpUnauthorizedResult();

            if (!_patterns.Validate(pattern))
            {
                _notifier.Error(T("Pattern is not valid."));
                ModelState.AddModelError("Pattern", T("Pattern is not valid.").Text);
                return Redirect(returnUrl);
            }

            _breadcrumbs.AddPattern(pattern, provider);
            _notifier.Information(T("Entry created successfully!"));

            return Redirect(returnUrl);
        }

        [HttpPost]
        [ActionName("MoveUp")]
        [ValidateAntiForgeryToken]
        public ActionResult MoveUp(int id)
        {
            return null;
        }

        [HttpPost]
        [ActionName("MoveUp")]
        [ValidateAntiForgeryToken]
        public ActionResult MoveDown(int id)
        {
            return null;
        }
    }
}

Views/BreadcrumbsAdmin/Index.cshtml
@model Onestop.Navigation.Breadcrumbs.ViewModels.BreadcrumbsIndexViewModel
@{
    Layout.Title = T("Manage route patterns for breadcrumbs").ToString();
    Script.Require("MenuAdminScripts");
    Style.Require("MenuAdmin");
}

<div class="row-fluid">
    <div class="sticky">
        <ul class="nav nav-pills">
            <li class="dropdown"><a class="btn-small dropdown-toggle" data-toggle="dropdown"
                href="#"><i class="icon-plus"></i>&nbsp;<b>@T("Add new pattern")</b></a>
                <div class="dropdown-menu dropdown-large">
                    @using (Html.BeginFormAntiForgeryPost(Url.Action("Add", "BreadcrumbsAdmin", new { area = "Onestop.Navigation", returnUrl = Request.RawUrl }), FormMethod.Post, new { @class = "form-horizontal" }))
                    {
                        <div class="control-group">
                            @Html.Label("Pattern", T("Pattern to add").Text, new { @class = "control-label" })
                            <div class="controls">
                                
                                @Html.TextBox("Pattern", "", new { @class = "input-xxlarge", placeholder = T("Type pattern here, eg. {slug}/{category}/{this|that}/{id}").Text  })
                                @Html.ValidationMessage("Pattern")
                                <span class="help-block">@T("Pattern to match page URLs against.")</span>
                            </div>
                        </div>
                        <div class="control-group">
                            @Html.Label("Provider", T("Choose provider").Text, new { @class = "control-label" })
                            <div class="controls">
                                
                                <select id="Provider" name="Provider" class="input-xlarge">
                                    @foreach (var p in Model.Providers)
                                    {
                                        @Html.SelectOption(null, p.Name, p.DisplayText)
                                    }
                                </select>
                                <span class="help-block">@T("Select a provider used to build breadcrumbs on all pages with URL matching a given pattern.")</span>
                            </div>
                        </div>
                        <div class="form-actions">
                            <input type="submit" class="btn button primaryAction pull-right" value="@T("Add")"/>
                        </div>
                    }
                </div>
            </li>
            <li class="dropdown pull-right"><a class="btn-small dropdown-toggle" data-toggle="dropdown"
                href="#"><i class="icon-question-sign"></i>&nbsp;<b>@T("Test pattern matching")</b></a>
                <div class="dropdown-menu dropdown-large">
                    @using (Html.BeginFormAntiForgeryPost(Url.Action("Index", "BreadcrumbsAdmin", new { area = "Onestop.Navigation" }), FormMethod.Post, new { @class = "form-inline" }))
                    {
                        <div class="pull-right">
                            @Html.TextBoxFor(m => m.TestString, new { @class = "input-xlarge", placeholder = T("Type string to test here...").Text })
                            <button type="submit" name="submit.Test" class="btn button primaryAction" value="yes">@T("Test!")</button>
                        </div> 
                    }
                </div>
            </li>
        </ul>
    </div>
</div>
<fieldset>
    <legend>@T("Current patterns")</legend>
    <table class="items">
        <thead>
            <th>@T("Pattern")</th>
            <th>@T("Provider")</th>
            <th></th>
            <th></th>
        </thead>
        @foreach (var pattern in Model.Patterns)
        {
            var provider = Model.Providers.FirstOrDefault(p => p.Name.Equals(pattern.Provider, StringComparison.OrdinalIgnoreCase));
            <tr>
                <td>
                    <b>@pattern.Pattern</b>

                </td>
                <td>
                    @if (provider != null)
                    {
                        @provider.DisplayText
                    }
                    else
                    {
                        <i>Non-existent provider</i>
                    }
                </td>
                <td>
                    @if (Model.Matches.ContainsKey(pattern.Pattern))
                    {
                        var match = Model.Matches[pattern.Pattern];
                        if (match.IsMatch)
                        {
                        <b>@T("Match!")</b>
                            if (match.Groups.Any())
                            {
                        <span class="hint">@T("Found groups:")
                            <ul>
                                @foreach (var group in match.Groups)
                                {
                                    <li><b>@group.Key</b>: @group.Value</li>
                                }
                            </ul>
                        </span>
                            }
                        }
                        else
                        {
                        @T("No match")
                        }
                    }
                </td>
                <td class="actions">
                    @if (pattern.Editable)
                    {
                        @Html.ActionLink(T("Delete").Text, "Delete", new {id = pattern.Id, returnUrl = Request.RawUrl}, new {itemprop = "RemoveUrl UnsafeUrl"})
                    }
                    @if (pattern.Global)
                    {
                        @Html.ActionLink(T("Go to global settings").Text, "Index", "Admin", new{ area = "Settings", groupInfoId = "Navigation", returnUrl = Request.RawUrl}, new {})
                    }
                </td>
            </tr>
        }
    </table>
</fieldset>

